### ISSUE TITLE
Ошибка при запуске Охоты

### ISSUE THREAD

**Issue by 18augst** [Novator/Pandora#14]
Жму на кнопку охоты, выдает:

    "==reconn: [#<TCPSocket:fd 15>, nil]|1:[false]"
    "LISTEN: [\"127.0.0.1\", \"127.0.0.1\", 45278, \"tcp\"]"
    "==reconn: [#<TCPSocket:fd 16>, nil]|1:[false]"
    "HUN: add_send_segment:  [ascmd, ascode, asbuf.bytesize]=[1, 0, 47]"
    "HUN: ЦИКЛ ОТПРАВКИ начало: @conn_state=1"
    "HUN: SEND_ALL: [index, cmd, code, lengt]=[0, 1, 0, 47]"
    "HUN: Цикл ЧТЕНИЯ сокета начало"
    "HUN: Цикл ЧТЕНИЯ начало"
    "[51, 47, 51]"
    #<PandoraNet::Session:0x00000000bff6f8>
    "LIS: ЦИКЛ ОТПРАВКИ начало: @conn_state=1"
    ./pandora.rb:2572:in `[]': no implicit conversion of PandoraNet::Session into Integer (TypeError)
    	from ./pandora.rb:2572:in `block in get_block_from_queue'
    	from ./pandora.rb:2567:in `synchronize'
    	from ./pandora.rb:2567:in `get_block_from_queue'
    	from ./pandora.rb:7179:in `block in initialize'

**Comment by Novator** [comment]
Случайно из ветки разработки (develop) код попал в основную (master) ветку.
Я исправил ошибку - должно заработать. Попробуйте!

**Comment by 18augst** [comment]
Ок, сейчас обновлюсь с мастера, попробую.
