### ISSUE TITLE
Добавить статьи о сети Pandora в блог на ZeroNet

### ISSUE THREAD

**Issue by Gutalean** [Novator/Pandora#18]
Здравствуйте!

Приглашаем вас зайти в p2p сеть ZeroNet и выложить там статьи о Pandora. В сеть можно попасть как через гейтвей (http://bit.no.com:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D)
так и напрямую, скачав установщик с сайта Zeronet.io.

Специальная тема на русском форуме тут: http://bit.no.com:43110/1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE/?Topic:4_1PvAyLAB5H1JKbiFjx95ZJXrNJVyWxs5Hf/

**Comment by Novator** [comment]
Я считаю, веб должен сдохнуть. Представление информации в виде веб-страницы - это эволюционный тупик. Веб-страница - это запутанная, оторванная от реальной жизни, форма представления информации, к тому же технически несовместимая с понятием "децентрализация".

На мой инженерный взгляд единицей информации в децентрализованной сети может быть только четко структурированный объект (запись): "Человек", "Город", "Статья", "Файл", "Товар", "Объявление", "Расписка", "Проект", "Постановление", "Закон", "Мнение" и так далее.

Обмен такими объектами более экономичен в плане трафика и вынуждает людей к большей ответственности и созидательной активности. Обмен четкими объектами вынуждает людей заниматься делом, а не балду пинать в аморфном вебе.

Web must die!
