### ISSUE TITLE
Crashes on Start ubuntu 17

### ISSUE THREAD

**Issue by chromax** [Novator/Pandora#22]
i 've installed it on ubuntu using the instruction but the client crashes everytime i try to start it

**Comment by Novator** [comment]
Hi!
Open terminal and run manually:
/opt/pandora/pandora.sh

You will see error strings. Paste and copy them here, please.

**Comment by Novator** [comment]
PPA repository is obsolete (it contents version 0.60).
Now version 0.69 is actual. You can download new code:
https://github.com/Novator/Pandora/archive/master.zip

Unpack it and overwrite files to /opt/pandora/

**Comment by Novator** [comment]
@chromax, so, did you resolve an error?
