### ISSUE TITLE
habr? блог?

### ISSUE THREAD

**Issue by 221V** [Novator/Pandora#23]
Здравствуйте!

а куда пропали с хабра все ваши статьи?
и ваш личный блог тоже пропал...

что случилось???

**Comment by 221V** [comment]
http://blog.robux.biz/2013/07/pandora-install-and-first-run.html
бросает переадресацию на http://www6.robux.biz

**Comment by 221V** [comment]
понял, есть
https://robux-biz.blogspot.com/
итого просто домен robux.biz пропал, а блог доступен на старом субдомене

**Comment by Novator** [comment]
Да, верно (я только сейчас увидел вопрос здесь).
