### ISSUE TITLE
Mac Instructions no longer work

### ISSUE THREAD

**Issue by crunchysteve** [Novator/Pandora#27]
I've just tried following the Mac OS install instructions and several of the dependencies won't install. I suspect that, for just one example, GTK2 probably hasn't been ported to Apple Silicon ARM architecture.

**Comment by Novator** [comment]
Hi. You need to run this command successful:
**gem install gtk2**

As I remember Ruby 3.1 was the last version which supports Gtk2.
So, you should lower a version of Ruby if you want to install gtk2.
Alternative way is to use other OS, Linux or Windows (with non-last Ruby of course).

**Comment by crunchysteve** [comment]
Thanks, I did try downgrading GTK and it wasn't allowed. At least on instructions I could find. Anyway, looking at other options, for the moment.Cheers,CrunchyMake things, travel and tell stories.On 18 Jul 2023, at 7:23 pm, Michael Galyuk ***@***.***> wrote:﻿
Hi. You need to run this command successful:
gem install gtk2
As I remember Ruby 3.1 was the last version which supports Gtk2.
So, you should lower a version of Ruby if you want to install gtk2.
Alternative way is to use other OS, Linux or Windows (with non-last Ruby of course).

**Comment by Novator** [comment]
Actually, you need only two instruction for all OS:
**gem install sqlite3
gem install gtk2**
If they done fine you have a huge chance to launch Pandora.

Also I've never touch MacOS, all instructions which you see in README.TXT were received from other users or found by me in google.

**Comment by crunchysteve** [comment]
Ok, thanks for the clarification. 🙂

**Comment by crunchysteve** [comment]
Yeah, neither work. I'm on an M1 mac, so I guess the Apple Silicon ARM64
architecture breaks it. I've found a lot of Mac support in the linux world
lately doesn't factor for this. Fair enough, not your platform, not your
monkeys. Thanks for the help, though. Guess this ticket can be closed. I'm
following up other, but similar tools, now.

**Comment by Novator** [comment]
Gtk2 is declared as "obsolete". It and its bindings are broken in lot of OS now. I will not transit to Gtk3, because of Gtk3 is pared-down and unstable s**t. Also Pandora is abandoned project now, I have no resources and wishes to develop it. Thanks for attention anyway.
