### ISSUE TITLE
Версия для Mac OS X

### ISSUE THREAD

**Issue by silvansky** [Novator/Pandora#3]
Я бы с удовольствием потестил Пандору под макосью.

В будущем можно было бы и для iOS сделать клиент.

**Comment by djsmentya** [comment]
Стартанула на Mac OS X Yosemite 10.10.2

    brew install Caskroom/cask/xquartz
    gem install gtk2
    # путь может менятся пока не знаю как ссылку на DISPLAY укаывать автоматически
    export DISPLAY=/private/tmp/com.apple.launchd.B1Gc3NQXZr/org.macosforge.xquartz\:0 
    ./pandora.sh

**Comment by Novator** [comment]
@djsmentya, Пандора-таки запустилась на Маке или нет?

**Comment by Novator** [comment]
Если да, то как вы узнаёте это путь:
/private/tmp/com.apple.launchd.B1Gc3NQXZr/org.macosforge.xquartz\:0
?

**Comment by djsmentya** [comment]
@Novator, да запустилась, путь узнаю заходя в папку `/private/tmp` и ищу папку с файлом `org.macosforge.xquartz:0` - там у меня всего 3 папки так что мне найти не сложно. нужно понять как с XQuartz  получить путь к DISPLAY

**Comment by Novator** [comment]
Я не для себя - для маководов спрашиваю )
А вобще, было бы неплохо добавить строчку в ./pandora.sh для маков.
Вот только какую?

**Comment by Novator** [comment]
Добавил в ./pandora.sh такой код:

# OS dependent initialization
case "$OSTYPE" in
  darwin*)  #Macosx
    export DISPLAY=/private/tmp/com.apple.launchd.*/org.macosforge.xquartz\:0
    ;;
esac

Попробуйте, маководы - может заработает.

**Comment by Novator** [comment]
Добавил в ./pandora.sh такой код:

  # OS dependent initialization
  case "$OSTYPE" in
    darwin) #Macosx
      export DISPLAY=/private/tmp/com.apple.launchd.*/org.macosforge.xquartz\:0
      ;;
  esac

Возможно, нужно написать:
  export DISPLAY=/private/tmp/com.apple.launchd.??????????/org.macosforge.xquartz\:0

Ну или как-то ещё. Попробуйте.
И мне сообщите.

**Comment by Novator** [comment]
Добавил в ./pandora.sh такой код:

    # OS dependent initialization
    case "$OSTYPE" in
      darwin) #Macosx
        export DISPLAY=/private/tmp/com.apple.launchd.*/org.macosforge.xquartz\:0
        ;;
    esac

Возможно, нужно написать:
    export DISPLAY=/private/tmp/com.apple.launchd.??????????/org.macosforge.xquartz\:0

Ну или как-то ещё. Попробуйте.
И мне сообщите.

**Comment by Novator** [comment]
Добавил в ./pandora.sh такой код:

    # OS dependent initialization
    case "$OSTYPE" in
      darwin) #Macosx
        export DISPLAY=/private/tmp/com.apple.launchd.*/org.macosforge.xquartz\:0
        ;;
    esac

Возможно, нужно написать:

    export DISPLAY=/private/tmp/com.apple.launchd.??????????/org.macosforge.xquartz\:0

Ну или как-то ещё. Попробуйте.
И мне сообщите.

**Comment by Novator** [comment]
Улучшил, пробуйте:

     # OS dependent initialization
     case "$OSTYPE" in
       darwin*)  #Macosx
         DISPTH=`find /private/tmp -path /private/tmp/com.apple.launchd.*/org.macosforge.xquartz -print`
         export DISPLAY=$DISPTH\:0
         ;;
     esac

**Comment by djsmentya** [comment]
надо убрать тот код, после установки xquartz нужно перезагрузится и переменная DISPLAY будет сама установлена как надо

**Comment by Novator** [comment]
@djsmentya, ещё вопрос: как вы устанавливали ruby и gtk на свою МакОС?

**Comment by Novator** [comment]
Т.е. вобще не надо ничо инициализировать? (А я так старасё O:-)

**Comment by djsmentya** [comment]
ruby через rbenv а gtk гемом `gem install gtk2` похоже гем сам скомпилировал все нужные библиотеки

**Comment by djsmentya** [comment]
извиняюсь, не знал что надо рестарт сделать после установки xquartz

**Comment by Novator** [comment]
@djsmentya, а что значит "ruby через rbenv"?
Я хочу в README.TXT добавить мануал.

**Comment by Novator** [comment]
В этих ваших маках нет штатного Менеджера пакетов?

**Comment by djsmentya** [comment]
штатного нет, но есть xcode который включает в себя ruby так что ни rvm ни rbenv не нужен впринципе
установку можно свести к следующим командам (если устанавливаем на чистую операционную систему):

    xcode-select --install
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" # установка homebrew 
    brew install Caskroom/cask/xquartz #установка xquartz
    # перезагрузка ОС
    gem install gtk2
    ./pandora.sh

**Comment by Novator** [comment]
О, отлично! Спасибо. Щас допилю shell и может даже в ридми добавлю.

**Comment by Novator** [comment]
А sudo перед gem надо писать? Например:

    sudo gem install gtk2

**Comment by Novator** [comment]
Всё. Добработал README.TXT и pandora.sh,
надеюсь, теперь маководы заживут хорошо.

**Comment by Novator** [comment]
Мужики, а для Макосикса можно пакет сделать? Что-то наподобе deb-пакета?

**Comment by Novator** [comment]
Погуглил, в маке есть утилита PackageMaker.app
Она и позволяет запилить установочный пакет (например, Pandora.pkg):
http://ctrld.me/blog/2009/11/26/sozdanie-ustanovochnyx-paketov-packagemaker/
http://snowosx.blogspot.ru/2011/03/pkg.html

Счастливые обладатели маков могут сделать пакет и поделиться.
Но я уверен, что этого никто не сделает, поэтому закрываю топик.
